### ISSUE TITLE
JsonDispatcher misuses @Tag annotation

### ISSUE THREAD

**Issue by vanam** [contributte/apitte-skeleton#255]
I believe that `Apitte\Core\Annotation\Controller\Tag` annotation was created for documentation purpose (or at least it is used for OpenAPI definition generation). Therefore, all request bodies cannot have the same name "request.dto".

[`App\Model\Api\Dispatcher\JsonDispatcher`](https://github.com/contributte/apitte-skeleton/blob/master/app/model/Api/Dispatcher/JsonDispatcher.php#L91-L94)
```php
		// Get incoming request entity class, if defined. Otherwise, skip transforming.
		if (!($entity = $endpoint->getTag('request.dto'))) {
			return $request;
		}
```

**Comment by f3l1x** [comment]
It's merged. Can we close it?

**Comment by vanam** [comment]
Unfortunatelly no. I haven't fix it with #256

**Comment by Pryx** [comment]
@vanam Any plans to address this? If not, I might take a stab at this.

**Comment by vanam** [comment]
@Pryx Feel free to fix it. :muscle:

**Comment by f3l1x** [comment]
Merged
