### ISSUE TITLE
Service of type Contributte\Middlewares\Application\IApplication not found. 

### ISSUE THREAD

**Issue by MilanTuryna** [contributte/apitte-skeleton#645]
Hi, I installed apitte-skeleton on apache without docker and now when I run application I get this exception.

Internal Server Error
On Tracy: \MissingServiceException: Service of type Contributte\Middlewares\Application\IApplication not found.

Before I have also problem with 
Error: Call to undefined method Symfony\Component\Validator\ValidatorBuilder::enableAnnotationMapping()
but thats now somehow ok.

I feel like my computer trolls me. Does anyone know what to do? Thanks.

**Comment by f3l1x** [comment]
That's weird. There is test case for that.

https://github.com/contributte/apitte-skeleton/blob/696cead3747d02bacb66687bf53c5a7b2902883f/tests/Cases/E2E/Container/EntrypointTest.php#L6

It's passing on master.

**Comment by MilanTuryna** [comment]
Thanks, there was a problem in my composer, for some reason it installed the packages incomplete, when I tried again on a different environment, it works.
