### ISSUE TITLE
Symfony AnnotationLoader missing

### ISSUE THREAD

**Issue by lukasbruha** [contributte/apitte-skeleton#663]
AnnotationLoader has been deprecated for a while in < 7. It has been replaced by AttributeLoader since then. 

Please, change `symfony.serializer.annotationLoader` in services.neon from `Symfony\Component\Serializer\Mapping\Loader\AnnotationLoader` to `Symfony\Component\Serializer\Mapping\Loader\AttributeLoader`.

**Comment by f3l1x** [comment]
Resolved, thanks.
